from django.urls import path, include
from . import views

urlpatterns = [
 path("", views.home, name="home"),
 path("news/<str:slug>/<int:pk>/", views.detail, name="detail"),
 path("list/", views.list, name="list"),
 path("about/", views.about, name="about"),
 path("contact/", views.contact, name="contact"),
 path("dashboard/", views.dashboard, name="dashboard"),
 path("accounts/", include("django.contrib.auth.urls")),
 path("edit_news/<int:pk>/", views.edit_news, name="edit_news"),
 path("add_news/", views.add_news, name="add_news"),
 path("news_list/", views.news_list, name="news_list"),
 path("delete_news/<int:pk>/", views.delete_news, name="delete_news"),
 path("edit_ads/<int:pk>/", views.edit_ads, name="edit_ads"),
 path("delete_youtube/<int:pk>/", views.delete_youtube, name="delete_youtube"),
 path("edit_youtube/<int:pk>/", views.edit_youtube, name="edit_youtube"),
 path("ads_list/", views.ads_list, name="ads_list"),
 path("job/", views.job, name="job"),
 path("slider_ads_list/", views.slider_ads_list, name="slider_ads_list"),
 path("details_ads_list/", views.details_ads_list, name="details_ads_list"),
 path("left_ads_list/", views.left_ads_list, name="left_ads_list"),
 path("right_ads_list/", views.right_ads_list, name="right_ads_list"),
 path("top_ads_list/", views.top_ads_list, name="top_ads_list"),
 path("center_ads_list/", views.center_ads_list, name="center_ads_list"),
 path("youtube_list/", views.youtube_list, name="youtube_list"),
 path("add_youtube/", views.add_youtube, name="add_youtube"),
 path("youtube/", views.youtube, name="youtube"),
 path("tc/", views.tc, name="tc"),
 path("pp/", views.pp, name="pp"),
 path("add_job/", views.add_job, name="add_job"),
 path("list_job/", views.list_job, name="list_job"),
 path("dashboard_settings/", views.dashboard_settings, name="dashboard_settings"),
 path("delete_job/<int:pk>/", views.delete_job, name="delete_job"),
 path("edit_job/<int:pk>/", views.edit_job, name="edit_job"),
 path("job_details/<int:pk>/", views.job_details, name="job_details"),
 path("author_details/<int:pk>/", views.author_details, name="author_details"),
 path('rss.xml', views.LatestNewsFeed(), name='news_rss'),
  path('register-author/', views.register_author, name='register_author'),
  path('tags/', views.tags, name='tags'),
  path('author_list/', views.author_list, name='author_list'),
 path("profile_detail/<int:pk>/", views.profile_detail, name="profile_detail"),
 path("edit_profile/<int:pk>/", views.edit_profile, name="edit_profile"),
 path("password_reset/<int:pk>/", views.password_reset, name="password_reset"),
 path("delete_user/<int:pk>/", views.delete_user, name="delete_user"),
 path("comment_list/", views.comment_list, name="comment_list"),
 path("delete_comment/<int:pk>/", views.delete_comment, name="delete_comment"),
 path("news_visitor_chart/<int:pk>/", views.news_visitor_chart, name="news_visitor_chart"),
]