# Generated by Django 5.1.1 on 2025-10-15 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/ads')),
                ('is_active', models.BooleanField(default=True)),
                ('ads_type', models.CharField(blank=True, choices=[('Details', 'Details'), ('Left', 'Left'), ('Right', 'Right'), ('Slider', 'Slider'), ('List', 'List'), ('Top', 'Top'), ('Ad1', 'Ad1'), ('Ad2', 'Ad2'), ('Ad3', 'Ad3'), ('Ad4', 'Ad4'), ('Ad5', 'Ad5')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=50)),
                ('about_role', models.TextField()),
                ('responsibilities', models.TextField(help_text='Use line breaks for each responsibility.')),
                ('skills', models.TextField(help_text='Use line breaks for each skill.')),
                ('qualifications', models.TextField(help_text='Use line breaks for each qualification.')),
                ('benefits', models.TextField(help_text='Use line breaks for each benefit.')),
                ('email', models.EmailField(max_length=254)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_jobs', models.BooleanField(default=True)),
                ('show_youtube', models.BooleanField(default=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('x_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('threads_link', models.URLField(blank=True, null=True)),
                ('snapchat_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
                ('reddit_link', models.URLField(blank=True, null=True)),
                ('discord_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('dribbble_link', models.URLField(blank=True, null=True)),
                ('behance_link', models.URLField(blank=True, null=True)),
                ('arattai_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Youtube',
                'verbose_name_plural': 'Youtube',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Sub_heading', models.TextField(blank=True, default='')),
                ('Description', models.TextField()),
                ('Location', models.CharField(blank=True, choices=[('India', 'India'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Kerala', 'Kerala'), ('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad'), ('Karnataka', 'Karnataka'), ('Bagalkote', 'Bagalkote'), ('Ballari', 'Ballari'), ('Belagavi', 'Belagavi'), ('Bengaluru Rural', 'Bengaluru Rural'), ('Bengaluru Urban', 'Bengaluru Urban'), ('Bidar', 'Bidar'), ('Chamarajanagara', 'Chamarajanagara'), ('Chikkaballapura', 'Chikkaballapura'), ('Chikkamagaluru', 'Chikkamagaluru'), ('Chitradurga', 'Chitradurga'), ('Dakshina Kannada', 'Dakshina Kannada'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Gadag', 'Gadag'), ('Hassan', 'Hassan'), ('Haveri', 'Haveri'), ('Kalaburagi', 'Kalaburagi'), ('Kodagu', 'Kodagu'), ('Kolar', 'Kolar'), ('Koppal', 'Koppal'), ('Mandya', 'Mandya'), ('Mysuru', 'Mysuru'), ('Raichur', 'Raichur'), ('Ramanagara', 'Ramanagara'), ('Shivamogga', 'Shivamogga'), ('Tumakuru', 'Tumakuru'), ('Udupi', 'Udupi'), ('Uttara Kannada', 'Uttara Kannada'), ('Vijayanagara', 'Vijayanagara'), ('Vijayapura', 'Vijayapura'), ('Yadgiri', 'Yadgiri')], default='', max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Political', 'Political'), ('Crime', 'Crime'), ('Local', 'Local'), ('State', 'State'), ('Central', 'Central')], default='Political', max_length=20)),
                ('Image_1', models.ImageField(upload_to='upload/')),
                ('Image_2', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('Image_3', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('Image_4', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('Image_5', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('Image_6', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('display_author', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='news', max_length=255, null=True)),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='base.author')),
                ('tags', models.ManyToManyField(blank=True, to='base.tag')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.news')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
