# Generated by Django 5.1.1 on 2025-10-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='base.news')),
            ],
            options={
                'unique_together': {('news', 'date')},
            },
        ),
    ]
