# Generated by Django 5.1.1 on 2025-10-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_newsvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_type',
            field=models.CharField(blank=True, choices=[('Details', 'Details'), ('Left', 'Left'), ('Right', 'Right'), ('Slider', 'Slider'), ('Top', 'Top'), ('Ad1', 'Ad1'), ('Ad2', 'Ad2'), ('Ad3', 'Ad3'), ('Ad4', 'Ad4'), ('Ad5', 'Ad5')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Category',
            field=models.CharField(choices=[('Political', 'Political'), ('Crime', 'Crime'), ('Local', 'Local'), ('State', 'State'), ('Central', 'Central'), ('World', 'World'), ('Business', 'Business'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Health', 'Health'), ('Environment', 'Environment'), ('Science', 'Science'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Culture', 'Culture'), ('Weather', 'Weather'), ('Opinion', 'Opinion'), ('Others', 'Others')], default='Political', max_length=20),
        ),
    ]
